-- Journal ("/journal" on whatisbrand0_site) — self-serve posts table.
-- Run in the Supabase SQL editor for the artist_archetype_reference
-- project (qumnkvyzqsmgwznohuld.supabase.co) -- the SAME project
-- creative-relatives-matcher.js reads artist rows from on brand0-site.
-- Not the results/access-codes project (xrgpmpniagxlspndiqvf.supabase.co).
--
-- Publishing a post = inserting one row here with `published_at` set (or
-- editing an existing one). No code changes, no new files, ever. Leaving
-- `published_at` null keeps a post as an unpublished draft -- it exists in
-- the table but the public SELECT policy below won't expose it.
--
-- `slides` is a JSON array -- one journal post renders as a full-screen
-- scroll-snap slide deck (same mechanic as brand0-site's kidlaroi.html /
-- the quiz results deck), not a normal scrolling article. Each element:
--   { "kind": "intro" | "text" | "reveal" | "quote" | "image" | "signoff",
--     "eyebrow": "optional small label above the title",
--     "title": "optional heading",
--     "body": ["optional", "paragraphs", "one string each"],
--     "image_url": "optional, used by kind:image (and as a background accent on other kinds)",
--     "caption": "optional, shown under an image" }
-- journal-post.html renders unrecognized/omitted fields gracefully, so this
-- can grow later without a migration.

create table if not exists public.journal_posts (
  id            bigint generated by default as identity primary key,
  slug          text unique not null,
  title         text not null,
  dek           text,               -- one-line dek/excerpt, shown on the /journal listing card
  author        text,
  cover_image_url text,             -- listing-card thumbnail
  slides        jsonb not null default '[]'::jsonb,
  published_at  timestamptz,        -- null = draft, not publicly visible
  created_at    timestamptz not null default now()
);

alter table public.journal_posts enable row level security;

-- Public can only ever see published posts -- drafts (published_at is
-- null) or scheduled-future posts stay invisible to the anon key used by
-- journal.html / journal-post.html.
drop policy if exists "Public can read published journal posts" on public.journal_posts;
create policy "Public can read published journal posts"
  on public.journal_posts
  for select
  to anon, authenticated
  using (published_at is not null and published_at <= now());
